<?php

	//init
	require_once "./custom/tool/initialize/system_tables.php";
//	require_once "./custom/tool/initialize/sampleInit.php";	
	

	//update
	
//	require_once "./custom/tool/update/1_0_0_1.php";
	require_once "./custom/tool/update/add_sub_update.php";
	require_once "./custom/tool/update/job_station_update.php";
	require_once "./custom/tool/update/page_file_rename.php";
	require_once "./custom/tool/update/jc1tojc2_update.php";